goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../reagent/interop.js", ['reagent.interop'], ['cljs.core']);
goog.addDependency("../reagent/debug.js", ['reagent.debug'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../reagent/impl/util.js", ['reagent.impl.util'], ['reagent.interop', 'cljs.core', 'reagent.debug', 'clojure.string']);
goog.addDependency("../reagent/ratom.js", ['reagent.ratom'], ['reagent.impl.util', 'cljs.core']);
goog.addDependency("../react.inc.js", ['cljsjs.react'], []);
goog.addDependency("../reagent/impl/batching.js", ['reagent.impl.batching'], ['reagent.impl.util', 'reagent.interop', 'reagent.ratom', 'cljs.core', 'reagent.debug', 'clojure.string']);
goog.addDependency("../reagent/impl/component.js", ['reagent.impl.component'], ['reagent.impl.util', 'reagent.interop', 'reagent.ratom', 'cljs.core', 'reagent.impl.batching', 'reagent.debug']);
goog.addDependency("../reagent/impl/template.js", ['reagent.impl.template'], ['reagent.impl.util', 'reagent.interop', 'reagent.ratom', 'cljs.core', 'reagent.impl.batching', 'reagent.impl.component', 'reagent.debug', 'clojure.string']);
goog.addDependency("../reagent/core.js", ['reagent.core'], ['reagent.impl.util', 'reagent.interop', 'reagent.ratom', 'cljs.core', 'cljsjs.react', 'reagent.impl.template', 'reagent.impl.batching', 'reagent.impl.component', 'reagent.debug']);
goog.addDependency("../dict_chrome/locale_codes.js", ['dict_chrome.locale_codes'], ['cljs.core']);
goog.addDependency("../dict_chrome/locales.js", ['dict_chrome.locales'], ['reagent.core', 'cljs.core', 'dict_chrome.locale_codes']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../ajax/core.js", ['ajax.core'], ['goog.net.XhrManager', 'goog.net.XhrIo', 'goog.Uri.QueryData', 'goog.Uri', 'cljs.core', 'goog.net.EventType', 'goog.structs', 'goog.json.Serializer', 'clojure.string', 'cljs.reader', 'goog.events', 'goog.net.ErrorCode']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../dict_chrome/api_client.js", ['dict_chrome.api_client'], ['ajax.core', 'cljs.core', 'dict_chrome.locales', 'clojure.walk']);
goog.addDependency("../dict_chrome/active_view.js", ['dict_chrome.active_view'], ['reagent.core', 'cljs.core']);
goog.addDependency("../dict_chrome/translation.js", ['dict_chrome.translation'], ['reagent.core', 'cljs.core', 'dict_chrome.locales', 'dict_chrome.api_client', 'clojure.walk', 'dict_chrome.active_view']);
goog.addDependency("../dict_chrome/typeahead.js", ['dict_chrome.typeahead'], ['goog.async.Throttle', 'reagent.core', 'cljs.core', 'dict_chrome.translation', 'dict_chrome.locales', 'dict_chrome.api_client', 'dict_chrome.active_view']);
goog.addDependency("../dict_chrome/options.js", ['dict_chrome.options'], ['reagent.core', 'cljs.core', 'dict_chrome.locales']);
goog.addDependency("../dict_chrome/popup.js", ['dict_chrome.popup'], ['reagent.core', 'dict_chrome.typeahead', 'cljs.core', 'dict_chrome.translation', 'dict_chrome.locales']);